services:

  php-webhooksample:
    container_name: php-webhooksample
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8100:80
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/conf.d/custom.ini
